@startuml
title UC-08 - DFD: Quản lý nhật ký chăm sóc
rectangle "Người dùng" as User
rectangle "Thiết bị nhập" as Input
usecase "Quản lý nhật ký chăm sóc" as Process
rectangle "Thiết bị xuất" as Output
database "Bộ nhớ phụ" as Storage
User --> Process : D1
Process --> User : D6
Input --> Process : D2
Process --> Output : D5
Storage --> Process : D3
Process --> Storage : D4
@enduml
